MvcApplication1/Controllers/BtsubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class BtsubjectsController : Controller
    {
        private DCREntities db = new DCREntities();

        //
        // GET: /Btsubjects/

        public ActionResult Index(Int32 idprj)
        {
            return View(db.BTSUBJECT.ToList());
        }

        public IEnumerable<Carpeta> Carpetas_Listar(Int32 idprj, string sortOrder ) 
            {
             IEnumerable<Carpeta> subjs = (from m in db.BTSUBJECT
                        join n in db.BTITEMUSER on m.IdSubject equals n.IDITEM 
                        join p in db.RPPROJECTITEM on n.IDITEM equals p.ID 
                        join b in db.BTITEM on m.IdSubject equals b.ID  
                        where n.IDUSER == 17 &  p.IDPROJECT == idprj  & m.IdSubjectParent ==0 & m.SubjectType==2   //Cambiar 17 por User logged 
                       select new Carpeta {Id= m.IdSubject, IdParent= m.IdSubjectParent.Value ,Nombre =b.LOGICAL_NAME });
            

            switch (sortOrder)
            {
                case "_asc":
                    subjs = subjs.OrderBy(s => s.Nombre);
                    break;
                case "_desc":
                    subjs = subjs.OrderByDescending(s => s.Nombre);
                    break;
                default:
                    subjs = subjs.OrderBy(s => s.Nombre);
                    break;
            }


            foreach (Carpeta cp in subjs)
            {
                
                Byte[] imagen_stream = new Byte[0];
                string pathImgs = "/Images/";
                            

                DCREntities db1 = new DCREntities();
                BTIMAGES imgg = db1.BTIMAGES.Find(cp.Id);
                                                
               
                if (imgg !=null)
                {
                    imagen_stream = db1.BTIMAGES.Where(p => p.IdItem == cp.Id).SingleOrDefault().Picture;
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(imagen_stream);
                    //write to file

                    //pathImgs = pathImgs + "Img_" + cp.Id.ToString() + "_folder.jpg";
                    pathImgs = Request.MapPath("~/Images/") + "Img_" + cp.Id.ToString() + "_folder.jpg"; 

                    System.IO.FileStream file = new System.IO.FileStream(pathImgs, System.IO.FileMode.Create, System.IO.FileAccess.Write);
                    ms.WriteTo(file);
                    file.Close();
                    ms.Close();
                }
                else { pathImgs = pathImgs + "folder.jpg"; }
                ViewData[Convert.ToString(cp.Id)] = System.IO.Path.GetFileName(pathImgs);

            }

            return subjs.AsEnumerable();

            }

        public ActionResult Carpetas(Int32 idprj,string sortOrder)

        {
            ViewBag.prj = idprj;
            ViewBag.SortParm = String.IsNullOrEmpty(sortOrder) ? "_desc" : "";
            return View(Carpetas_Listar(idprj, sortOrder));
        }

        public IEnumerable<Carpeta> SubCarpetas_Listar(Int32 idfolder)
        {
            IEnumerable<Carpeta> subjs = (from m in db.BTSUBJECT
                                          join n in db.BTITEMUSER on m.IdSubject equals n.IDITEM
                                          join p in db.RPPROJECTITEM on n.IDITEM equals p.ID
                                          join b in db.BTITEM on m.IdSubject equals b.ID
                                          where n.IDUSER == 17 &  m.IdSubjectParent == idfolder & m.SubjectType == 2
                                          select new Carpeta { Id = m.IdSubject, Nombre = b.LOGICAL_NAME,IdParent=idfolder }).Union (
        //Procesos
                from m in db.BTSUBJECT_ITEMS
                join n in db.BTITEMUSER on m.IdItem equals n.IDITEM
                join p in db.RPPROJECTITEM on n.IDITEM equals p.ID
                join b in db.BTITEM on m.IdItem equals b.ID
                where n.IDUSER == 17 & m.IdSubject == idfolder & b.TYPE == 6   //Cambiar 17 por User logged 
                select new Carpeta { Id = m.IdItem, Nombre = b.LOGICAL_NAME,IdParent=-1 }                
                );
            //Reports

            foreach (Carpeta cp in subjs)
            {
                Byte[] imagen_stream = new Byte[0];
                
                string pathImgs= "/Images/";
               
                BTIMAGES imgg = db.BTIMAGES.Find(cp.Id);


                if (imgg != null)
                {
                    imagen_stream = db.BTIMAGES.Where(p => p.IdItem == cp.Id).SingleOrDefault().Picture;

                    System.IO.MemoryStream ms = new System.IO.MemoryStream(imagen_stream);
                    //write to file
                    pathImgs = Request.MapPath("~/Images/") + "Img_" + cp.Id.ToString() + "_folder.jpg";
                    //pathImgs = pathImgs+ "Img_" + cp.Id.ToString() + "_folder.jpg";
                    System.IO.FileStream file = new System.IO.FileStream(pathImgs, System.IO.FileMode.Create, System.IO.FileAccess.Write);
                    ms.WriteTo(file);
                    file.Close();
                    ms.Close();
                }
                else {
                pathImgs =pathImgs + "folder.jpg"; }
                ViewData[Convert.ToString(cp.Id)] = System.IO.Path.GetFileName(pathImgs); 

            }
            
            return subjs.AsEnumerable();
            
        }

        public ActionResult SubCarpetas(Int32 idprj,Int32 idpar)

        {
            Int32 idparFold = 0;
            BTSUBJECT_ITEMS idfolderP = db.BTSUBJECT_ITEMS.Where(a => a.IdItem == idpar).FirstOrDefault();
            if (idfolderP != null) {  idpar= idfolderP.IdSubject; }
            BTSUBJECT idfolderPar = db.BTSUBJECT.Where(a => a.IdSubject == idpar).FirstOrDefault();
            if (idfolderPar != null) { idparFold = idfolderPar.IdSubjectParent.Value; }
            

            ViewData["parFold"] = idparFold;
            ViewData["par"] = idpar;
            ViewData["prj"] = idprj;
            return View(SubCarpetas_Listar(idpar));
        }

        // GET: /Btsubjects/Details/5

        public ActionResult Details(int id = 0)
        {
            BTSUBJECT btsubject = db.BTSUBJECT.Find(id);
            if (btsubject == null)
            {
                return HttpNotFound();
            }
            return View(btsubject);
        }

        //
        // GET: /Btsubjects/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Btsubjects/Create

        [HttpPost]
        public ActionResult Create(BTSUBJECT btsubject)
        {
            if (ModelState.IsValid)
            {
                db.BTSUBJECT.Add(btsubject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(btsubject);
        }

        //
        // GET: /Btsubjects/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BTSUBJECT btsubject = db.BTSUBJECT.Find(id);
            if (btsubject == null)
            {
                return HttpNotFound();
            }
            return View(btsubject);
        }

        //
        // POST: /Btsubjects/Edit/5

        [HttpPost]
        public ActionResult Edit(BTSUBJECT btsubject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(btsubject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(btsubject);
        }

        //
        // GET: /Btsubjects/Delete/5

        public ActionResult Delete(int id = 0)
        {
            BTSUBJECT btsubject = db.BTSUBJECT.Find(id);
            if (btsubject == null)
            {
                return HttpNotFound();
            }
            return View(btsubject);
        }

        //
        // POST: /Btsubjects/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BTSUBJECT btsubject = db.BTSUBJECT.Find(id);
            db.BTSUBJECT.Remove(btsubject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Controllers/PrjuserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{   
    //[Authorize(Users=@"APENET\Administrador")]   // En caso de uso de Aut.Windows
    public class PrjuserController : Controller
    {
        
        private DCREntities db = new DCREntities();

        //
        // GET: /Prjuser/

        public IEnumerable<RPPROJECTSUSER> Py_Listar(string sGroupString)
        {

            sGroupString = "10,25,17";
            var myList = new List<string>(sGroupString.Split(','));
            IEnumerable<int> ListIDs = myList.Select(int.Parse).ToList();
            var usrs = from k in ListIDs select new RPPROJECTSUSER { IDUSER  = k };

            IEnumerable<RPPROJECTSUSER> v3 = (from c1 in
                     ((from c in db.RPPROJECTSUSER select c).ToList())
                      join c2 in usrs  
                      on c1.IDUSER 
                      equals c2.IDUSER 
                      select c1).ToList();

            IEnumerable<RPPROJECTSUSER> projs = (from m in v3
                                            where (m.TYPE == 5 )
                                            select new  RPPROJECTSUSER  {ID = m.ID  , LOGICAL_NAME  = m.LOGICAL_NAME, IDUSER  =m.IDUSER }) ;

            IEnumerable<RPPROJECTSUSER> projsG = from j in projs group j by j.LOGICAL_NAME into g select new RPPROJECTSUSER { LOGICAL_NAME = g.Key, ID = g.Max(d => d.ID) };
            return projsG;
        }

        public ActionResult Proyectos()
        {

            string sGroupString = "";
            sGroupString = AccountController.GetPerm(User);

            if (sGroupString != "La secuencia no contiene elementos")
            {
                ViewBag.NC = Properties.Settings.Default.ColumnsNum;

                IEnumerable<BTPROJECT> projects = (from j in db.BTPROJECT select j).ToList();
                return View(projects);
                //return View(Py_Listar(sGroupString));
            }
            else
            {
                return View("El usuario no tiene proyectos asignados");
            };
        }




        public ActionResult Index()
        {
        
            string sGroupString = "";
            sGroupString = AccountController.GetPerm(User) ;

           if (sGroupString !="La secuencia no contiene elementos") {
            return View(Py_Listar(sGroupString));} 
           else {
            return View("El usuario no tiene proyectos asignados");
            };
        }

        //
        // GET: /Prjuser/Details/5

        public ActionResult Details(Int32 id) 
        
        {
            
            RPPROJECTSUSER rpprojectsuser = db.RPPROJECTSUSER.Where(u => u.ID.Equals(id)).SingleOrDefault();
            if (rpprojectsuser == null)
            {
                return HttpNotFound();
            }
            return View(rpprojectsuser);
        }

        //
        // GET: /Prjuser/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Prjuser/Create

        [HttpPost]
        public ActionResult Create(RPPROJECTSUSER rpprojectsuser)
        {
            if (ModelState.IsValid)
            {
                db.RPPROJECTSUSER.Add(rpprojectsuser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rpprojectsuser);
        }

        //
        // GET: /Prjuser/Edit/5

        public ActionResult Edit(int id = 0)
 
        {
            BTPROJECT rpprojectsuser = db.BTPROJECT.Where(u => u.IDPROJECT.Equals(id)).SingleOrDefault();
            if (rpprojectsuser == null)
            {
                return HttpNotFound();
            }
            return View(rpprojectsuser);
        }

        //
        // POST: /Prjuser/Edit/5

        [HttpPost]
        public ActionResult Edit(BTPROJECT rpprojectsuser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rpprojectsuser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rpprojectsuser);
        }

        //
        // GET: /Prjuser/Delete/5

        public ActionResult Delete(int id = 0)
        {
            RPPROJECTSUSER rpprojectsuser = db.RPPROJECTSUSER.Find(id);
            if (rpprojectsuser == null)
            {
                return HttpNotFound();
            }
            return View(rpprojectsuser);
        }

        //
        // POST: /Prjuser/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            RPPROJECTSUSER rpprojectsuser = db.RPPROJECTSUSER.Find(id);
            db.RPPROJECTSUSER.Remove(rpprojectsuser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Views/Btsubjects/Carpetas.cshtml
@model IEnumerable<MvcApplication1.Models.Carpeta>

@{
    ViewBag.Title = "Carpetas";
    var nCarpeta = 0;
}
<h2>Carpetas</h2>

<p>
    @Html.ActionLink("  ","Index", "Prjuser",null, new { style = "background: url('" + Url.Content("~/Images/back.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })
 </p>

<table>
    <tr>
        <th>
          @Html.ActionLink("CARPETA", "Carpetas", new { idprj = ViewBag.prj, sortOrder = ViewBag.SortParm })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{

    if (nCarpeta == 0)
    {
    @: <tr>
    }

            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @if (item.IdParent > 0)
                {
                    var pathimg = "~/Images/" + ViewData[Convert.ToString(item.Id)].ToString();
                    @Html.ActionLink(" ", "Procesos", "Procesos", new { idfolder = item.Id, idfolderPar = item.IdParent }, new { style = "background: url('" + Url.Content(pathimg) + "') no-repeat center right; display:block; height:32px; width:32px;" })
                }
                else
                {
                    var pathimg = "~/Images/" + ViewData[Convert.ToString(item.Id)].ToString();
                    @Html.ActionLink(" ", "Procesos", "Procesos", new { idfolder = item.Id, idfolderPar = 0 }, new { style = "background: url('" + Url.Content(pathimg) + "') no-repeat center right; display:block; height:32px; width:32px;" })
                }
            </td>

     nCarpeta = nCarpeta + 1;
   
     if (nCarpeta == 4 || nCarpeta == Model.Count())
     {
     @: </tr>
     }
    

}     
</table>

MvcApplication1/Views/Btsubjects/Create.cshtml
@model MvcApplication1.BTSUBJECT

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BTSUBJECT</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdSubject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSubject)
            @Html.ValidationMessageFor(model => model.IdSubject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdSubjectParent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSubjectParent)
            @Html.ValidationMessageFor(model => model.IdSubjectParent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderN)
            @Html.ValidationMessageFor(model => model.OrderN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubjectType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubjectType)
            @Html.ValidationMessageFor(model => model.SubjectType)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Btsubjects/Details.cshtml
@model MvcApplication1.BTSUBJECT

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>BTSUBJECT</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdSubject)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdSubject)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdSubjectParent)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdSubjectParent)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderN)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderN)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SubjectType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubjectType)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcApplication1/Views/Btsubjects/Edit.cshtml
@model MvcApplication1.BTSUBJECT

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BTSUBJECT</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdSubject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSubject)
            @Html.ValidationMessageFor(model => model.IdSubject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdSubjectParent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSubjectParent)
            @Html.ValidationMessageFor(model => model.IdSubjectParent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderN)
            @Html.ValidationMessageFor(model => model.OrderN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubjectType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubjectType)
            @Html.ValidationMessageFor(model => model.SubjectType)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Btsubjects/Index.cshtml
@model IEnumerable<MvcApplication1.BTSUBJECT>

@{
    ViewBag.Title = "Index";
    
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Back", "Index")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSubjectParent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectType)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdSubject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdSubjectParent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderN)
        </td>
        <td>
           @Html.DisplayFor(modelItem => item.SubjectType) 
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        </td>
    </tr>
}

</table>

MvcApplication1/Views/Btsubjects/SubCarpetas.cshtml
@model IEnumerable<MvcApplication1.Models.Carpeta>

@{
    ViewBag.Title = "Subcarpetas";
    var prj = ViewData["prj"];
    var par = ViewData["par"];
    var parFold = ViewData["parFold"];
    var nCarpeta = 0;

}

<h2>SubCarpetas</h2>

<p>

    @if (parFold.Equals(0))
    {
    @Html.ActionLink(" ", "Carpetas", "Btsubjects", new { idprj = prj }, new { style = "background: url('" + Url.Content("~/Images/back.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })
    } else
    {
    @Html.ActionLink(" ", "SubCarpetas", "BtSubjects", new { idprj = prj, idPar = parFold }, new { style = "background: url('" + Url.Content("~/Images/back.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })
    }

</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{

    if (nCarpeta == 0)
    {
        @:
        <tr>
            }
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @if (item.IdParent > 0)
                {
                    var pathimg = "~/Images/" + ViewData[Convert.ToString(item.Id)].ToString();
                    @Html.ActionLink(" ", "SubCarpetas", "BtSubjects", new { idprj = prj, idPar = item.Id }, new { style = "background: url('" + Url.Content(pathimg) + "') no-repeat center right; display:block; height:32px; width:32px;" })

                }
                else
                {
                    @Html.ActionLink(" ", "RunPParams", "Params", new { procid = item.Id }, new { style = "background: url('" + Url.Content("~/Images/play_button.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })

                }
            </td>


            nCarpeta = nCarpeta + 1;

            if (nCarpeta == 4 || nCarpeta == Model.Count())
            {
            @:
        </tr>
    }
}

</table>