MvcApplication1/Controllers/ProcesosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class ProcesosController : Controller
    {
        private DCREntities db = new DCREntities();

        //
        // GET: /Procesos/

        public ActionResult Index()
        {
            return View(db.BTPROCESSEXCELREPORT.ToList());
        }

        public IEnumerable<BTITEM > Procesos_Listar(Int32 idfolder)
        {
       
        //Falta aplicar:
        //Case eSecurityMode.TreeSecurity, eSecurityMode.TotalAccessSecurity
        //    sError = "Error: El modelo de seguridad del usuario no está soportado"
        //End Select
            
        var myList = new List<string>(AccountController.GetPerm(User).Split(','));
        IEnumerable<int> ListIDs = myList.Select(int.Parse).ToList();
        var usrs = from k in ListIDs select new OPUSER  {IDUSUARIO  = k };
    
          
        IEnumerable<int> v2 = (from c1 in
                                      ((from c in db.BTSUBJECT_ITEMS select c).ToList())
                                      join c2 in db.BTITEMUSER
                                      on c1.IdItem
                                      equals c2.IDITEM where (c1.IdSubject == idfolder)
                                      join c3 in usrs on c2.IDUSER equals c3.IDUSUARIO
                                      select c1.IdItem).Distinct().ToList();

        IEnumerable<BTPROCESS> v3 = (from m in v2 join t in db.BTPROCESS on m equals t.IDPROCESS
                                 where (t.PROCESSCLASS == 12 | t.PROCESSCLASS == 2 | t.PROCESSCLASS == 11) && t.MyVisionVisible.Equals(true)
                                 select t).ToList();

        IEnumerable<BTITEM> procesoss = (from m in v3
                                                   join r in db.BTITEM on m.IDPROCESS  equals r.ID
                                                   select new BTITEM { ID  = r.ID, LOGICAL_NAME  = r.LOGICAL_NAME  }).Distinct().ToList();
                        return procesoss.AsEnumerable();
        }

        public ActionResult Procesos(Int32 idfolder,Int32 idfolderPar=0, bool LevelUP=false)
        {
            int idfparent;
            BTSUBJECT carp = db.BTSUBJECT.Where(c => c.IdSubjectParent == idfolder).FirstOrDefault();
            var idprj = db.RPPROJECTITEM.Where(p => p.ID == idfolder).FirstOrDefault().IDPROJECT;
            if (carp != null)
            {
                idfparent = carp.IdSubjectParent.Value;
                if (idfparent > 0)  //Si contiene subcarpetas
                {                   
                    return RedirectToAction("SubCarpetas", "BtSubjects", new { idprj = idprj, idpar= idfparent });
                }
            }

            BTSUBJECT_ITEMS idfolderP = db.BTSUBJECT_ITEMS.Where(a => a.IdItem == idfolder).FirstOrDefault();
            int idfolderProc = idfolder;
            if(idfolderP != null) { idfolderProc = idfolderP.IdSubject; }
            if (LevelUP) { idfolder = idfolderProc; };
            ViewData["prj"] = idprj;
            ViewData["carp"] = idfolder;
            if (idfolderPar == 0)
            {
                return View(Procesos_Listar(idfolder));
            }else
            {
                ViewData["carp"] = idfolderPar;
                return View(Procesos_Listar(idfolderPar));
            }


        }

        // GET: /Procesos/Details/5

        public ActionResult Details(int id = 0)
        {
            BTPROCESSEXCELREPORT btprocessexcelreport = db.BTPROCESSEXCELREPORT.Find(id);
            if (btprocessexcelreport == null)
            {
                return HttpNotFound();
            }
            return View(btprocessexcelreport);
        }

        //
        // GET: /Procesos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Procesos/Create

        [HttpPost]
        public ActionResult Create(BTPROCESSEXCELREPORT btprocessexcelreport)
        {
            if (ModelState.IsValid)
            {
                
                db.BTPROCESSEXCELREPORT.Add(btprocessexcelreport);
                db.SaveChanges();
              return RedirectToAction("Index");
            }

            return View(btprocessexcelreport);
        }

        //
        // GET: /Procesos/Run/5

        public ActionResult Run(string sParams,int id = 0 )
        {

                    string sMachineName = "PC"; //GetThisMachineName()
                    string sError = "";
                    //Demanem un nou ID per al job
                    int newJobID = GetFreeID(7, sError);
                    if (sError != "")
                    {
                        return RedirectToAction("Index");
                    };
                    string sIdUser = AccountController.GetUsrId(User).ToString();
                    string sParamString = sParams == null ? "" : sParams;
                    Int32 JobWaiting=0;
                    string TEST_ASAP = "TEST_PROCESS_ASAP";
   
                    string ssql = "INSERT INTO OPJOB(idJob , iduser, idServer, idPlan, IDProcess, idParentJob, Rootjob, Depth, EXECUTIONSTATUS, Trace_Level, UserParams)";
                    ssql = ssql + "VALUES (" + newJobID + "," + sIdUser + ",0, 0, " + id + ",0," + id + ",0, " + JobWaiting.ToString() + ",0, '" + sParamString.Replace("'", "''") + "') ";

                    int  newMessageID = GetFreeID(3, "");
                    //'Planifiquem el proces ASAP
                    string sInsertMessageSQL = "INSERT INTO COMUNICATOR (IDMessage, Moment, IDServer, Command, Param1, Param2, Param3, Priority, OriginIdUser, OriginMachineName, ServerLock)";
                    sInsertMessageSQL = sInsertMessageSQL + "VALUES (" + newMessageID + ",GetDate(),0,'" + TEST_ASAP + "','" + id + "','" + newJobID +"','" + sParamString.Replace("'", "''") + "',0," + sIdUser + ",'" + sMachineName + "',0)";
   

                    db.OPJOB.SqlQuery(ssql);
                    db.Database.ExecuteSqlCommand(ssql);
                    db.SaveChanges();
                    db.COMUNICATOR.SqlQuery(sInsertMessageSQL);
                    db.Database.ExecuteSqlCommand(sInsertMessageSQL);
                    db.SaveChanges();
            
                    return View();
        }
        

        [HttpPost]
        public ActionResult Run(BTPROCESSEXCELREPORT btprocessexcelreport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(btprocessexcelreport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(btprocessexcelreport);
        }


        //
        // GET: /Procesos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BTPROCESSEXCELREPORT btprocessexcelreport = db.BTPROCESSEXCELREPORT.Find(id);
            if (btprocessexcelreport == null)
            {
                return HttpNotFound();
            }
            return View(btprocessexcelreport);
        }

        //
        // POST: /Procesos/Edit/5

        [HttpPost]
        public ActionResult Edit(BTPROCESSEXCELREPORT btprocessexcelreport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(btprocessexcelreport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(btprocessexcelreport);
        }

        //
       

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public int  GetFreeID(int a, string e)
        {
            int rid;
            rid = -1;
            try
            {

                MAXIMO maxi = db.MAXIMO.SingleOrDefault(c=>c.IDTABLA== a);
                rid = maxi.MAXIMO1.Value;                             
                db.MAXIMO.Single(c=>c.IDTABLA== a).MAXIMO1  = rid+1;
                db.SaveChanges();
                
            }

            catch (Exception ex) 
            {
                e = ex.Message.ToString(); 

            }
            
            return rid;

        }
    }
}

MvcApplication1/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class ReportsController : Controller
    {
        private DCREntities db = new DCREntities();

        //
        // GET: /Reports/

        public ActionResult Index(int idp)

        {
            
    //sSQL = "SELECT max(BTITEMUSER.ViewResultsMode) as ViewResultsMode FROM BTITEMUSER WHERE IdItem = " & sIdProcess & " AND IDUSER IN (" & sGroupString & ")"
    //sViewResultModeXML = GetXMLData(sSQL, sError)
    //Set rsViewResultsMode = InternalRecordsetFromXMLString(sViewResultModeXML, adLockReadOnly, sError)
    //If Not rsViewResultsMode Is Nothing Then
    //    sViewResultsMode = IIf(IsNull(rsViewResultsMode.Fields("ViewResultsMode")), "", rsViewResultsMode.Fields("ViewResultsMode"))
        
    //    Select Case sViewResultsMode
    //        Case "1", "2":
    //            'Obtenim els reports de l'ultim job que tenen el nom y directori de generació diferents.
    //            'S'ha definit funció nova perquè ara BTREPORT té tots els reports on logicalfolder són diferents, aleshores tenim registres de + d'una
    //            'execució
    //            sSQL = "SELECT DISTINCT btreport.* from BTREPORT,"
    //            sSQL = sSQL & "(SELECT distinct logicalname,lastfilepath,max(lastidjob) as UltimoJob "
    //            sSQL = sSQL & " FROM BTREPORT INNER JOIN BTITEMUSER ON (BTITEMUSER.IdItem=BTReport.idProcess) WHERE"
    //            sSQL = sSQL & " ((BTITEMUSER.ViewResultsMode=1) OR (BTITEMUSER.ViewResultsMode=2 AND BTREPORT.IdVirtualExecutor=" & sUserId & ")) AND "
    //            sSQL = sSQL & "(BTREPORT.IdProcess =" & sIdProcess & ") AND (BTITEMUSER.IdUser IN (" & sGroupString & "))"
    //            sSQL = sSQL & " AND (BTREPORT.IsPublished=1)"
    //            sSQL = sSQL & " GROUP BY logicalname,lastfilepath) as t"
    //            sSQL = sSQL & " WHERE btreport.LogicalName = t.LogicalName And btreport.LastFilePath = t.LastFilePath And btreport.lastidjob = t.UltimoJob"
    //        Case "3":
    //            sSQL = "SELECT DISTINCT btreport.* from BTREPORT,"
    //            sSQL = sSQL & "(SELECT distinct logicalname,lastfilepath,max(lastidjob) as UltimoJob "
    //            sSQL = sSQL & " FROM BTREPORT INNER JOIN BTITEMUSER ON (BTITEMUSER.IdItem=BTReport.idProcess) WHERE"
    //            sSQL = sSQL & " (BTITEMUSER.ViewResultsMode=3) AND (BTREPORT.IdProcess =" & sIdProcess & ") AND (BTITEMUSER.IdUser IN (" & sGroupString & "))"
    //            sSQL = sSQL & " AND (BTREPORT.IsPublished=1)"
    //            sSQL = sSQL & " GROUP BY logicalname,lastfilepath) as t"
    //            sSQL = sSQL & " WHERE btreport.LogicalName = t.LogicalName And btreport.LastFilePath = t.LastFilePath And btreport.lastidjob = t.UltimoJob"
    //        Case Else:
    //            sError = "Nivel de seguridad desconocido"
    //    End Select
    //End If
    //sSQL = sSQL & " ORDER BY btreport.LastdateGen" 'FLC 20090701 - Cambios en la ordenación

            var myList = new List<string>(AccountController.GetPerm(User).Split(','));
            IEnumerable<int> ListIDs = myList.Select(int.Parse).ToList();
            var usrs = from k in ListIDs select new OPUSER { IDUSUARIO = k };

     
            IEnumerable<BTITEMUSER> v2 = (from c1 in
                                       ((from c in usrs select c).ToList())
                                   join c2 in db.BTITEMUSER
                                   on c1.IDUSUARIO 
                                   equals c2.IDUSER
                                   where (c2.IDITEM == idp)
                                   select c2).ToList() ;

            var vr = v2.Select(obj => obj.ViewResultsMode ).Max(); 

            ViewData["idproc"] =idp;
            var nombreproceso = db.BTITEM.Where(p => p.ID == idp).FirstOrDefault().LOGICAL_NAME;
            ViewData["nomproc"] = nombreproceso;

            switch (vr) 
	            {
	                case 1: case 2:  // es 1 o 2
	                {
                        IEnumerable<BTREPORT> v3 = (from c1 in
                                                     ((from c in v2 select c).ToList())
                                                      join c2 in db.BTREPORT
                                                      on c1.IDITEM 
                                                      equals c2.IdProcess
                                                    where ((c1.ViewResultsMode == 1) | (c1.ViewResultsMode == 2 & c2.IdVirtualExecutor == AccountController.GetUsrId(User))) & c2.IdProcess == idp & c2.IsPublished == true 
                                                      select c2).ToList().Distinct();
                        return View(v3.ToList().OrderByDescending(a => a.LastDateGen)) ;
		            }
	                case 3:

                     IEnumerable<BTREPORT> v4 = (from c1 in
                                                     ((from c in v2 select c).ToList())
                                                      join c2 in db.BTREPORT
                                                      on c1.IDITEM 
                                                      equals c2.IdProcess  
                                                      where c1.ViewResultsMode==3 & c2.IdProcess ==idp & c2.IsPublished ==true 
                                                      select c2).ToList().Distinct();
                        return View(v4.ToList().OrderByDescending(a => a.LastDateGen)) ;

	                default:
                    // You can use the default case.

                    
		            return View(db.BTREPORT.ToList().OrderByDescending(s => s.LastDateGen).Select(b=>b.IdProcess <0 ));
	            }
       
            //return View();
        }

        //
        // GET: /Reports/Details/5

        public ActionResult Details(int idp = 0)
        {
            BTREPORT btreport = db.BTREPORT.Find(idp);
            if (btreport == null)
            {
                return HttpNotFound();
            }
            return View(btreport);
        }

        //
        // GET: /Reports/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Reports/Create

        [HttpPost]
        public ActionResult Create(BTREPORT btreport)
        {
            if (ModelState.IsValid)
            {
                db.BTREPORT.Add(btreport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(btreport);
        }

        //
        // GET: /Reports/Edit/5

        public ActionResult Edit(int id = 0)
        {
            BTREPORT btreport = db.BTREPORT.Find(id);
            if (btreport == null)
            {
                return HttpNotFound();
            }
            return View(btreport);
        }

        //
        // POST: /Reports/Edit/5

        [HttpPost]
        public ActionResult Edit(BTREPORT btreport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(btreport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(btreport);
        }

        //
        

        public ActionResult Delete(int id = 0)
        {
            BTREPORT btreport = db.BTREPORT.Find(id);
            if (btreport == null)
            {
                return HttpNotFound();
            }
            return View(btreport);
        }

        //public ActionResult VistaReport(Int32 idrp)
        //{
        //    return GetReport(idrp);
        //}

        public bool RefReport()
        {
            return true;
        }


        public ActionResult GetReport(Int32 idrepo)
        {
            BTREPORT btreport = db.BTREPORT.Find(idrepo);
            
            if (btreport == null)
            {
                return PartialView("VistaNoReport"); 
            }
            
            return PartialView("VistaReport2", btreport );
        }

        
        public FileStreamResult DownloadFile(string fichero,string ruta)
        {
           
             
                string rutaf = ruta + "\\" + fichero; ;
                if (System.IO.File.Exists(rutaf))
                {
                    byte[] fileBytes = System.IO.File.ReadAllBytes(rutaf);
                    string fileName = rutaf.Substring(rutaf.LastIndexOf("\\"));

                    System.IO.FileStream fs = new System.IO.FileStream(rutaf, System.IO.FileMode.Open, System.IO.FileAccess.Read);
                    return File(fs, System.Net.Mime.MediaTypeNames.Application.Pdf);
                }
                else
                {
                return null;
            }

           
        
    }


        
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BTREPORT btreport = db.BTREPORT.Find(id);
            db.BTREPORT.Remove(btreport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
          }
    }
}

MvcApplication1/Views/Reports/Details.cshtml
@model MvcApplication1.BTREPORT

@{
    ViewBag.Title = "Details";
}

@Html.ActionLink("Back", "Index", new { idp = Model.IdReport })

<h2>Details</h2>

<fieldset>
    <legend>BTREPORT</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdReport)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdReport)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogicalName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogicalName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastFileType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastFileType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsCompressed)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsCompressed)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastIdFile)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastIdFile)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastIdJob)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastIdJob)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastFileName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastFileName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastFilePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastFilePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastDateGen)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastDateGen)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastFileSize)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastFileSize)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdProcess)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdProcess)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IdVirtualExecutor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdVirtualExecutor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsPublished)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsPublished)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogicalFolder)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogicalFolder)
    </div>
</fieldset>
<p>
   
   
</p>

MvcApplication1/Views/Reports/Edit.cshtml
@model MvcApplication1.BTREPORT

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BTREPORT</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdReport)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdReport)
            @Html.ValidationMessageFor(model => model.IdReport)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalName)
            @Html.ValidationMessageFor(model => model.LogicalName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastFileType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastFileType)
            @Html.ValidationMessageFor(model => model.LastFileType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsCompressed)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsCompressed)
            @Html.ValidationMessageFor(model => model.IsCompressed)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastIdFile)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastIdFile)
            @Html.ValidationMessageFor(model => model.LastIdFile)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastIdJob)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastIdJob)
            @Html.ValidationMessageFor(model => model.LastIdJob)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastFileName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastFileName)
            @Html.ValidationMessageFor(model => model.LastFileName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastFilePath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastFilePath)
            @Html.ValidationMessageFor(model => model.LastFilePath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastDateGen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastDateGen)
            @Html.ValidationMessageFor(model => model.LastDateGen)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastFileSize)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastFileSize)
            @Html.ValidationMessageFor(model => model.LastFileSize)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdProcess)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdProcess)
            @Html.ValidationMessageFor(model => model.IdProcess)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdVirtualExecutor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdVirtualExecutor)
            @Html.ValidationMessageFor(model => model.IdVirtualExecutor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsPublished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsPublished)
            @Html.ValidationMessageFor(model => model.IsPublished)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolder)
            @Html.ValidationMessageFor(model => model.LogicalFolder)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Reports/Index.cshtml
@model IEnumerable<MvcApplication1.BTREPORT>
@{
    var idp = ViewData["idproc"];
    ViewBag.Title = "Informes";
    
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src='@Url.Content("~/Scripts/jquery-2.0.3.js")' type="text/javascript"></script> 
    <script src="~/Scripts/jquery-1.8.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>


<p>
    @Html.ActionLink(" ", "Procesos", "Procesos", new { idfolder = idp, LevelUP = true }, new { style = "background: url('" + Url.Content("~/Images/back.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })
</p>

<h2>Reports</h2><h3> (Proceso:@ViewData["nomproc"])</h3>
@if (Model.Count() == 0)
{  <h3>No existen Informes</h3>

}
else { 
<div id="Visor">
    @Html.Partial("VistaReport2", Model.FirstOrDefault())
</div>

<table>
    <tr>    <th> NAME </th>    <th> DATE </th>     <th> SIZE </th></tr>

@foreach (var item in Model) {
    <tr>
      <td>
            @Ajax.ActionLink(item.LogicalName.ToString() , "GetReport",
                            new { idrepo = item.IdReport },
                            new AjaxOptions()
                            {
                                HttpMethod = "POST",
                                UpdateTargetId = "Visor",
                                InsertionMode = InsertionMode.Replace,
                            })
    </td>

        <td> @Html.DisplayFor(modelItem => item.LastDateGen)    </td>
        <td> @Html.DisplayFor(modelItem => item.LastFileSize.Value ) </td>
        <td>
            @Html.ActionLink("Descarga", "DownloadFile", new { fichero=item.LastFileName, ruta=item.LastFilePath  }) |
            @Html.ActionLink("Details", "Details", new {  idp=item.IdReport  }) 
        </td>
    </tr>
}
</table>

}

MvcApplication1/Views/Reports/VistaNoReport.cshtml
<p>No existe informe</p>