MvcApplication1/Controllers/ParamsController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{

    public enum eDatabaseType
    {
        DB_TYPE_ACCESS = 1,     //Access
        DB_TYPE_TEXT,           //Fitxer texte
        DB_TYPE_EXCEL,          //Fitxer excel
        DB_TYPE_ODBC,           //Connexió via ODBC
        DB_TYPE_DBASE_III,      //Connexió a dBase III
        DB_TYPE_DBASE_IV,       //Connexió a dBase IV
        DB_TYPE_DBASE_V,        //Connexió a dBase V
        DB_TYPE_WK4,            //Connexió a fitxer Lotus 1-2-3
        DB_TYPE_EXCEL2007,      //Connexió a EXCEL 2007
        DB_TYPE_ACCESS2007,     //Connexió a ACCESS 2007
        DB_TYPE_EXCEL2010,      //Connexió a EXCEL 2010
        DB_TYPE_ACCESS2010      //Connexió a ACCESS 2010
    }
    
    public class ParamsController : Controller
    {

        //    Retorna el string de conexió a la base de dades a partir de l'identificador de la base de dades

        private Int32 sIdDatabaseQuery;
        private string GetODBCConnectionString(int sConnectionModus, string sConnectionstring, string sOdbcDSN, string sODBCDriver, string sLogin, string sPassword, string sOdbcServerName, string sOdbcDatabaseName, string sError)

        {
            string conStr = "";

            switch (sConnectionModus)
            {
                case 1: //Modus_ConnectionString
                    conStr = sConnectionstring;
                    conStr = conStr + "UID=" + sLogin + ";";
                    conStr = conStr + "PWD=" + sPassword + ";";
                    return conStr;

                case 2: // Modus_ConnectToDSN
                    conStr = "DSN=" + sOdbcDSN + ";";
                    conStr = conStr + "UID=" + sLogin + ";";
                    conStr = conStr + "PWD=" + sPassword + ";";
                    conStr = conStr + "OLE DB Services= -2;";       //Això és basic per evitar el Pooling (caché) de conexions
                    return conStr;
                case 3: // Modus_ConnectToDriver
                    //conStr = "Driver={" + sODBCDriver + "};";
                    conStr = conStr + "Server=" + sOdbcServerName + ";";
                    conStr = conStr + "Database=" + sOdbcDatabaseName + ";";
                    conStr = conStr + "UID=" + sLogin + ";";
                    conStr = conStr + "PWD=" + sPassword + ";";
                    return conStr;
                default:
                    return conStr;
            }

        }


        public string GetConnectionString(int sIDDataBase, int sDataEngine, string sError)
        {

            var conxDatos = (from x in db.BTDATABASE
                             where (x.IDDATABASE == sIDDataBase)
                             select x).ToList();
            int sDatabaseType, sConnectionModus;
            string sConnectionStringOptions, sFileName;
            string sSystemFile, sLogin, sPassword, sConnectionString, sOdbcDSN, sODBCDriver, sOdbcServerName, sOdbcDatabaseName;
            if (conxDatos != null)
            {
                try
                {
                    sConnectionModus = conxDatos.LastOrDefault().ConnectModus.Value;
                    sDatabaseType = conxDatos.LastOrDefault().SGBD.Value;
                    sFileName = conxDatos.LastOrDefault().FilePath.ToString();
                    sSystemFile = conxDatos.LastOrDefault().CONNSYSTEM.ToString();
                    sLogin = conxDatos.LastOrDefault().CONNLOGIN.ToString();
                    sPassword = conxDatos.LastOrDefault().CONNPASSWORD.ToString();
                    sConnectionString = conxDatos.LastOrDefault().CONNSTRCONNECTION.ToString();
                    sOdbcDSN = conxDatos.LastOrDefault().CONNPASSWORD.ToString();
                    sODBCDriver = conxDatos.LastOrDefault().ConnectDriver.ToString();
                    sOdbcServerName = conxDatos.LastOrDefault().SERVIDOR.ToString();
                    sOdbcDatabaseName = conxDatos.LastOrDefault().DatabaseName.ToString();
                    
                    switch ((eDatabaseType)sDatabaseType)
                    {

                        case eDatabaseType.DB_TYPE_ODBC:
                            sError = "";
                            return GetODBCConnectionString(sConnectionModus, sConnectionString, sOdbcDSN, sODBCDriver, sLogin, sPassword, sOdbcServerName, sOdbcDatabaseName, sError);
                            
                        case eDatabaseType.DB_TYPE_TEXT:
                            sError = "";
                            return "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + sFileName + ";Extended Properties='text';";
                        case eDatabaseType.DB_TYPE_EXCEL:
                            sError = "";
                            if (sDataEngine == 1) { sConnectionStringOptions = "Excel 8.0;HDR=NO;IMEX=2"; }
                            else
                            { //dao350
                                sConnectionStringOptions = "Excel 8.0;HDR=YES;IMEX=2";
                            }

                            return "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + sFileName + ";Extended Properties=" + sConnectionStringOptions + "";
                        case eDatabaseType.DB_TYPE_DBASE_III:
                        case eDatabaseType.DB_TYPE_DBASE_IV:
                        case eDatabaseType.DB_TYPE_DBASE_V:
                        case eDatabaseType.DB_TYPE_WK4:
                            sError = "";
                            return "";
                        case eDatabaseType.DB_TYPE_ACCESS:
                            if (sSystemFile.Length > 0) { return "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + sFileName + ";"; }
                            else
                            { return "Provider=Microsoft.Jet.OLEDB.4.0;User ID=" + sLogin + ";Password=" + sPassword + ";Data Source=" + sFileName + ";"; }

                        case eDatabaseType.DB_TYPE_EXCEL2007:
                        case eDatabaseType.DB_TYPE_EXCEL2010:
                            sConnectionStringOptions = "Excel 12.0;HDR=NO;IMEX=0";
                            return "Provider=Microsoft.ACE.OLEDB.12.0;" + "Data Source=" + sFileName + ";Extended Properties='" + sConnectionStringOptions + "'";
                        case eDatabaseType.DB_TYPE_ACCESS2007:
                        case eDatabaseType.DB_TYPE_ACCESS2010:
                            return "Provider=Microsoft.ACE.OLEDB.12.0;" + "Data Source=" + sFileName;
                        default:
                            return "";
                    }
                }
                catch (Exception ex)
                {
                    sError = ex.Message + ",No se ha encontrado un perfil de base de datos con Id=" + sIDDataBase;
                    return "";
                }
            }

            else
            {
                sError = "No se ha encontrado un perfil de base de datos con Id=" + sIDDataBase;
                return "";
            }
        }


        private DCREntities db = new DCREntities();


        private MultiSelectList GetParamValues(Int32 idparam)
        {
            var ParamValues = (from x in
                                   ((from y in db.BTITEMPARAM select y).ToList())
                               join z in db.BTPARAMTYPEDOMAINVALUES
                               on x.ParamType
                               equals z.IdParamType
                               where (x.IdParam == idparam)
                               select z).ToList();


            return new MultiSelectList(ParamValues, "DomainValue", "ValueUserText");
        }

        public MultiSelectList GetParamValuesFromDB(Int32 idqCall)
        {

            try {
                Dictionary<string, string> ParamValuesDB = new Dictionary<string, string>();
                var queryData = db.BTQUERYCALL.Where(p => p.IdQueryCall == idqCall);
                var queryData2 = db.BTQUERY.Where(q => q.IDQUERY == queryData.FirstOrDefault().IdQuery).FirstOrDefault();

                string conx = GetConnectionString(queryData2.IDDATABASE.Value, queryData2.DATA_ENGINE.Value, "");
                
                string sError = "";
                string sParamString = "";
                Collection<Param> ParamSet;
                ParamSet = DecompressParam(sParamString, ref sError);

                //return null;

                LoadParamsOfItemFromDB(queryData2.IDQUERY, idqCall, ParamSet);
                DateTime moment = DateTime.Now;
                DefineTimeContextParams(moment, ref ParamSet);     //Estableix el valors de tots els paràmetres que dependen del temps.

                //sIdDatabaseQuery = sIDDataBase

                string sSQL = queryData2.QUERY.ToString();
                var queryData3 = db.RPPROJECTITEM.Where(p => p.ID == queryData2.IDQUERY).FirstOrDefault();

                int UserId = AccountController.GetUsrId(User);
                sSQL = Preprocess(sSQL, ParamSet, UserId.ToString(), queryData3.IDPROJECT, sError);
                
                if (conx.Contains("OLEDB"))
                {

                    System.Data.OleDb.OleDbConnection sqlconn = new System.Data.OleDb.OleDbConnection(conx);
                    System.Data.OleDb.OleDbCommand sqlcmd = new System.Data.OleDb.OleDbCommand(sSQL, sqlconn);
                    using (sqlconn)
                    {
                        sqlconn.Open();
                        using (System.Data.OleDb.OleDbDataReader reader = sqlcmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                if (reader.FieldCount == 1)
                                {
                                    ParamValuesDB.Add(Convert.ToString(reader[1]), Convert.ToString(reader[1]));

MvcApplication1/Views/Procesos/Edit.cshtml
@model MvcApplication1.BTPROCESSEXCELREPORT

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BTPROCESSEXCELREPORT</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.idReportExcel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.idReportExcel)
            @Html.ValidationMessageFor(model => model.idReportExcel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FilePath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FilePath)
            @Html.ValidationMessageFor(model => model.FilePath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TemplatePath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TemplatePath)
            @Html.ValidationMessageFor(model => model.TemplatePath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MessageSubject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MessageSubject)
            @Html.ValidationMessageFor(model => model.MessageSubject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MessageBody)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MessageBody)
            @Html.ValidationMessageFor(model => model.MessageBody)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdMailProfile)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdMailProfile)
            @Html.ValidationMessageFor(model => model.IdMailProfile)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MailType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MailType)
            @Html.ValidationMessageFor(model => model.MailType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SendMail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SendMail)
            @Html.ValidationMessageFor(model => model.SendMail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FreeMailAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FreeMailAddress)
            @Html.ValidationMessageFor(model => model.FreeMailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ATTACHMENTTYPE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ATTACHMENTTYPE)
            @Html.ValidationMessageFor(model => model.ATTACHMENTTYPE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GENERATEOLE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GENERATEOLE)
            @Html.ValidationMessageFor(model => model.GENERATEOLE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.REPORT_FILE_TYPE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REPORT_FILE_TYPE)
            @Html.ValidationMessageFor(model => model.REPORT_FILE_TYPE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.APPEND_DATA)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.APPEND_DATA)
            @Html.ValidationMessageFor(model => model.APPEND_DATA)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.COMPRESS_REPORT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.COMPRESS_REPORT)
            @Html.ValidationMessageFor(model => model.COMPRESS_REPORT)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FileName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FileName)
            @Html.ValidationMessageFor(model => model.FileName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DELETE_ZIP)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DELETE_ZIP)
            @Html.ValidationMessageFor(model => model.DELETE_ZIP)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NUM_RECORDS_TO_COMMIT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NUM_RECORDS_TO_COMMIT)
            @Html.ValidationMessageFor(model => model.NUM_RECORDS_TO_COMMIT)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DELETE_REPORT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DELETE_REPORT)
            @Html.ValidationMessageFor(model => model.DELETE_REPORT)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AttatchReportToMail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AttatchReportToMail)
            @Html.ValidationMessageFor(model => model.AttatchReportToMail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AttatchZipReportToMail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AttatchZipReportToMail)
            @Html.ValidationMessageFor(model => model.AttatchZipReportToMail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreateDir)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreateDir)
            @Html.ValidationMessageFor(model => model.CreateDir)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdPerfilPub)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdPerfilPub)
            @Html.ValidationMessageFor(model => model.IdPerfilPub)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdPerfilPub_Zip)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdPerfilPub_Zip)
            @Html.ValidationMessageFor(model => model.IdPerfilPub_Zip)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolder)
            @Html.ValidationMessageFor(model => model.LogicalFolder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolderId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolderId)
            @Html.ValidationMessageFor(model => model.LogicalFolderId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolderCreate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolderCreate)
            @Html.ValidationMessageFor(model => model.LogicalFolderCreate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolderPermissionType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolderPermissionType)
            @Html.ValidationMessageFor(model => model.LogicalFolderPermissionType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogicalFolderPermissionParam)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogicalFolderPermissionParam)
            @Html.ValidationMessageFor(model => model.LogicalFolderPermissionParam)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Procesos/Index.cshtml
@model IEnumerable<MvcApplication1.BTPROCESSEXCELREPORT>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idReportExcel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TemplatePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MessageSubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MessageBody)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdMailProfile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MailType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SendMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FreeMailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ATTACHMENTTYPE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GENERATEOLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REPORT_FILE_TYPE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.APPEND_DATA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMPRESS_REPORT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DELETE_ZIP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NUM_RECORDS_TO_COMMIT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DELETE_REPORT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AttatchReportToMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AttatchZipReportToMail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDir)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdPerfilPub)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdPerfilPub_Zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicalFolder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicalFolderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicalFolderCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicalFolderPermissionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogicalFolderPermissionParam)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idReportExcel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TemplatePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MessageSubject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MessageBody)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdMailProfile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MailType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SendMail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FreeMailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ATTACHMENTTYPE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GENERATEOLE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.REPORT_FILE_TYPE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.APPEND_DATA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMPRESS_REPORT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DELETE_ZIP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NUM_RECORDS_TO_COMMIT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DELETE_REPORT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AttatchReportToMail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AttatchZipReportToMail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDir)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdPerfilPub)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdPerfilPub_Zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicalFolder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicalFolderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicalFolderCreate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicalFolderPermissionType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogicalFolderPermissionParam)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

MvcApplication1/Views/Procesos/Procesos.cshtml
@model IEnumerable<MvcApplication1.BTITEM>
@{
    ViewBag.Title = "Procesos";
    var idpr = ViewData["prj"];
    var idcarp = ViewData["carp"];

}
<h2>Procesos</h2>

<p>
    @Html.ActionLink(" ", "Carpetas", "Btsubjects", new {idprj= idpr}, new { style = "background: url('" + Url.Content("~/Images/back.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;" })
   
</p>
<table>
   @* <tr><th></th><th></th></tr>*@

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.LOGICAL_NAME)</td>
        <td>@Html.ActionLink(" ", "RunPParams", "Params", new { procid=item.ID},  new { style = "background: url('" + Url.Content("~/Images/play_button.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;"})</td>  @*//new {@class="buttplay" } )*@
        @*<td>@Html.ActionLink(" ","Run" , new {sParams="", id=item.ID},  new { style = "background: url('" + Url.Content("~/Images/play_button.jpg") + "') no-repeat center right; display:block; height:32px; width:32px;"})</td> *@
        <td>@Html.ActionLink(" ", "Index","Reports", new { idp = item.ID }, new { style = "background: url('" + Url.Content("~/Images/icon_excel.png") + "') no-repeat center right; display:block; height:32px; width:32px;"})</td>
    </tr>
}

</table>
@if (Model.Count() == 0)
{
    <h3>No existen Procesos</h3>}